name: Lint
on:
  push:
    branches:
      - '**'
  # pull_request:
  #   types: [opened, synchronize]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 14
      uses: actions/setup-node@v1
      with:
        node-version: 14
    - name: upgrade npm
      run: npm install -g npm
    - name: npm install
      run: npm install
    - name: npm run lint
      run: npm run lint
